<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <RootNamespace>CadLens.AutoCAD</RootNamespace>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/CadLens.Common/CadLens.Common.csproj" />
        <ProjectReference Include="../../src/CadLens.UI/CadLens.UI.csproj" />
        <Compile Include="../../src/AutoCAD/CadLens.AutoCAD/Services/AutoCadEntitySnapshotReader.cs" Link="AutoCadEntitySnapshotReader.cs" />
        <Compile Include="../../src/AutoCAD/CadLens.AutoCAD/Services/AutoCadDrawingInventorySource.cs" Link="AutoCadDrawingInventorySource.cs" />
        <Compile Include="../../src/AutoCAD/CadLens.AutoCAD/Services/ObjectExplorerActions.cs" Link="ObjectExplorerActions.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Models/EntityId.cs" Link="EntityId.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Models/LayerId.cs" Link="LayerId.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Abstractions/IEntityIsolationActions.cs" Link="IEntityIsolationActions.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Abstractions/IEntityIsolationService.cs" Link="IEntityIsolationService.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Abstractions/IHostTaskService.cs" Link="IHostTaskService.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Services/AutoCadTaskService.cs" Link="AutoCadTaskService.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Services/EntityIsolationService.cs" Link="EntityIsolationService.cs" />
        <Compile Include="../../src/CadLens.Common.AutoCAD/Extensions/DatabaseObjectExtensions.cs" Link="DatabaseObjectExtensions.cs" />
    </ItemGroup>
</Project>