<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <UseUi>true</UseUi>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../CadLens.Lenses/CadLens.Lenses.csproj"/>
        <Resource Include="Resources/CadLens.png"/>
    </ItemGroup>

</Project>
