<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <UseUi>true</UseUi>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../CadLens.Core/CadLens.Core.csproj"/>
        <ProjectReference Include="../CadLens.Lenses/CadLens.Lenses.csproj"/>
    </ItemGroup>

</Project>