<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseAutocad>true</UseAutocad>
        <UseWPF>true</UseWPF>
        <UseDi>true</UseDi>
        <UseJson>true</UseJson>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../CadLens.Common.AutoCAD/CadLens.Common.AutoCAD.csproj"/>
        <ProjectReference Include="../../CadLens.Lenses/CadLens.Lenses.csproj"/>
        <ProjectReference Include="../../CadLens.UI/CadLens.UI.csproj"/>
    </ItemGroup>
</Project>
